dashboard-square-01=f1b15
user-group=f2923
teacher=f27cb
quiz-01=f23e2
book-open-01=f176d
chart-histogram=f1924
award-01=f1674
user-settings-01=f2936
logout-01=f1ffb
refresh=f244e
add-01=f150c
download-01=f1bb4
filter-reset=f1cc4
edit-02=f1c02
archive-01=f15e3
lock-password=f1fec
login-01=f1ff3
user-add-01=f2914
image-upload=f1e9e
user-circle=f291d
play=f2348
floppy-disk=f1cf5
upload-01=f28fb
analytics-01=f15bd
view=f2971
delete-02=f1b35
cancel-01=f18bc
user=f2949
arrow-left-01=f1612
